In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

from sentence_transformers import SentenceTransformer

# Awalan

In [ ]:
df_cv = pd.read_csv('sample_10_cv_with_ground_truth.csv')
df_job = pd.read_csv('data_clean.csv')

In [4]:
df_cv.head()

,candidate_name,email,phone,skills,summary,experience,degree,university,Category,text_for_tfidf,text_for_embed,text_for_embed_with_punctuation,ground_truth
0,Rina Putri,rina.putri@example.com,6281234567890,"kepemimpinan, google workspace, kerja tim, mic...",dokter umum yang berdedikasi dengan pengalaman...,lebih dari 3 tahun di pelayanan kesehatan pri...,S1,universitas indonesia jakarta lulus dengan pre...,Healthcare,summary dedicated general practitioner 3 years...,summary dedicated general practitioner with mo...,summary: dedicated general practitioner with m...,"dokter umum, nurse, medical representative"
1,Siti Rahayu,siti.rahayu@email.com,62812345678900,asisten keperawatan magang februari 2023 - mei...,-,"dalam memberikan perawatan dasar, mendampingi ...",-,-,Healthcare,summary experience providing basic care accomp...,summary experience in providing basic care acc...,"summary: experience: in providing basic care, ...","perawat, staff nurse (perawat), private homeca..."
2,Rina Hidayati,rina.hidayati@email.com,6281123456789,"lorem ipsum corp jakarta, software sertifikasi...",seorang profesional call center dengan pengala...,lebih dari 2 tahun dalam menangani keluhan pe...,SMA,-,Customer Service,summary call center professional 2 years exper...,summary a call center professional with more t...,summary: a call center professional with more ...,"customer service, customer relationship office..."
3,Rina Sari,rina.sari@example.com,6281234567890,"kepemimpinan, matlab, excel, perancangan prose...",-,"dalam penelitian, analisis data, dan perancang...",S1,universitas pendidikan indonesia bandung ipk,Data,summary experience research data analysis proc...,summary experience in research data analysis a...,"summary: experience: in research, data analysi...",data analyst for production staff (code : prod...
4,Rizal Alfian,rizal.alfian@example.com,6281234567890,"hmt elektro upi bandung, autocad electrical, r...",-,"dalam desain sirkuit dan pengujian perangkat, ...",S1,universitas pendidikan indonesia bandung ipk,Engineering,summary experience circuit design device testi...,summary experience in circuit design and devic...,summary: experience: in circuit design and dev...,"engineering staff, electrical engineering (kos..."

In [5]:
df_job.head()

,Posisi,Perusahaan,Lokasi,Type,Gaji,Requirements,Link,text_for_tfidf,text_for_embed,text_for_embed_with_punctuation
0,Tenaga Admin,PT Serdang Baja Makmur Abadi,Medan,Full time,Rp 3.250.000 – Rp 3.500.000 per month,Pekerjaan administrasi umum seperti membuat In...,https://id.jobstreet.com/id/job/91338594?type=...,admin staff admin staff general administrative...,admin staff general administrative work such a...,admin staff general administrative work such a...
1,Admin Operasional & HR Support (MAGANG),PT Saptakarsa Prima,Kecamatan Tangerang,Full time,Rp 2.500.000 – Rp 3.500.000 per month,Pendidikan minimal SMK Jurusan Administrasi Pe...,https://id.jobstreet.com/id/job/91309622?type=...,admin operational hr support internship admin ...,admin operational hr support internship educat...,admin operational hr support internship educat...
2,Executive admin,Pengiklan Anonim,Jakarta Utara,Full time,Rp 4.700.000 – Rp 5.500.000 per month,Mengelola kalender dan jadwal eksekutif dengan...,https://id.jobstreet.com/id/job/91479903?type=...,executive admin executive admin manages execut...,executive admin manages executive calendars an...,executive admin manages executive calendars an...
3,Executive admin,Pengiklan Anonim,Jakarta Utara,Full time,Rp 4.700.000 – Rp 5.500.000 per month,"Mengelola jadwal, pertemuan, dan kegiatan ekse...",https://id.jobstreet.com/id/job/91508884?type=...,executive admin executive admin manages meetin...,executive admin manages meeting schedules and ...,executive admin manages meeting schedules and ...
4,Operations & Admin Coordinator (Indonesia Repr...,Pengiklan Anonim,Cilandak,Full time,Rp 6.500.000 – Rp 8.500.000 per month,Manage daily administrative tasks; Organize do...,https://id.jobstreet.com/id/job/91487019?type=...,operations admin coordinator indonesia represe...,operations admin coordinator indonesia represe...,operations admin coordinator indonesia represe...

In [6]:
df_cv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   candidate_name                   10 non-null     object
 1   email                            10 non-null     object
 2   phone                            10 non-null     int64
 3   skills                           10 non-null     object
 4   summary                          10 non-null     object
 5   experience                       10 non-null     object
 6   degree                           10 non-null     object
 7   university                       10 non-null     object
 8   Category                         10 non-null     object
 9   text_for_tfidf                   10 non-null     object
 10  text_for_embed                   10 non-null     object
 11  text_for_embed_with_punctuation  10 non-null     object
 12  ground_truth                     10 non-null     object
dtypes: int64(1), object(12)
memory usage: 1.1+ KB

In [7]:
df_job.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 10 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Posisi                           1400 non-null   object
 1   Perusahaan                       1400 non-null   object
 2   Lokasi                           1400 non-null   object
 3   Type                             1400 non-null   object
 4   Gaji                             1400 non-null   object
 5   Requirements                     1400 non-null   object
 6   Link                             1400 non-null   object
 7   text_for_tfidf                   1400 non-null   object
 8   text_for_embed                   1400 non-null   object
 9   text_for_embed_with_punctuation  1400 non-null   object
dtypes: object(10)
memory usage: 109.5+ KB

In [8]:
# df_cv_clean = df_cv.drop_duplicates(subset=['candidate_name'])
# df_cv_undersampling = df_cv_clean.sample(n=10, random_state=42).reset_index(drop=True)
# df_cv_undersampling

In [9]:
# df_cv_undersampling.to_csv('sample_10_cv.csv', index=False)

# TF-IDF

In [10]:
job_texts = df_job["text_for_tfidf"].tolist()

In [11]:
vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    sublinear_tf=True
)

job_tfidf = vectorizer.fit_transform(job_texts)

In [12]:
for h in range(10):
    print("-"*40)
    print(f"BARIS {h+1}")
    print("-"*40)
    cv_text = df_cv.loc[h, 'text_for_tfidf']
    cv_tfidf = vectorizer.transform([cv_text])

    scores = cosine_similarity(cv_tfidf, job_tfidf)

    top_k = 5
    top_indices = scores[0].argsort()[-top_k:][::-1]

    for i in top_indices:
        print("Perusahaan:", df_job.iloc[i]["Perusahaan"])
        print("Posisi:", df_job.iloc[i]["Posisi"])
        print("Score:", scores[0][i])
        print("-"*40)

    print("\n")

----------------------------------------
BARIS 1
----------------------------------------
Perusahaan: Serrebeauty
Posisi: Dokter Umum
Score: 0.2805980835611086
----------------------------------------
Perusahaan: RS Awal Bros Group
Posisi: Kepala Departemen Penunjang Medis
Score: 0.27447319106128015
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Private Homecare Nurse
Score: 0.2727134085762191
----------------------------------------
Perusahaan: RS Firdaus
Posisi: Perawat
Score: 0.24000719734249729
----------------------------------------
Perusahaan: PT. Meimo Toronta Sera
Posisi: HOSPITAL MANAGER ( Pre Opening)
Score: 0.22250251831881596
----------------------------------------


----------------------------------------
BARIS 2
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Private Homecare Nurse
Score: 0.3616282862230051
----------------------------------------
Perusahaan: RS Firdaus
Posisi: Perawat
Score: 0.25756608059456326
----------------------------------------
Perusahaan: Klinik Sakti Medika
Posisi: Perawat Bedah
Score: 0.1992531002470321
----------------------------------------
Perusahaan: PT GENOMIK SOLIDARITAS INDONESIA
Posisi: Perawat Perusahaan
Score: 0.182211445469524
----------------------------------------
Perusahaan: MAYAPADA HEALTHCARE
Posisi: HEAD OF MAYAPADA CLINIC
Score: 0.18036505019594867
----------------------------------------


----------------------------------------
BARIS 3
----------------------------------------
Perusahaan: PT ASURANSI SIMAS JIWA
Posisi: Customer Service Sharia (Contract)
Score: 0.25884641051911794
----------------------------------------
Perusahaan: Nusa Medica Clinic
Posisi: Call Center Officer
Score: 0.25250789015872643
----------------------------------------
Perusahaan: PT. Berkat Skala Sejahtera
Posisi: Sales Corporate
Score: 0.2237538628681265
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Customer Service
Score: 0.20457859416177415
----------------------------------------
Perusahaan: PT Aldmic Indonesia
Posisi: Customer Service
Score: 0.20140739258437088
----------------------------------------


----------------------------------------
BARIS 4
----------------------------------------
Perusahaan: PT Waterpro Mandiri International
Posisi: Process Engineer (WTP & WWTP)
Score: 0.19294035712359686
----------------------------------------
Perusahaan: OPPO Indonesia
Posisi: Industrial Engineer
Score: 0.18777350672419194
----------------------------------------
Perusahaan: PT Airtekindo Prima
Posisi: ENGINEERING HVAC SUPERVISOR
Score: 0.17387966185256623
----------------------------------------
Perusahaan: Poly Arta Chemicals
Posisi: SALES MARKETING KIMIA INDUSTRI
Score: 0.1665937525005781
----------------------------------------
Perusahaan: PT Cakra Daya Makmur
Posisi: RnD Cosmetic
Score: 0.16401807851177652
----------------------------------------


----------------------------------------
BARIS 5
----------------------------------------
Perusahaan: PT. Sarana Meditama International (EMC Healthcare Group)
Posisi: AI Application Officer
Score: 0.1772868244496228
----------------------------------------
Perusahaan: PT Rukun Persada Makmur
Posisi: IT
Score: 0.1685384463276526
----------------------------------------
Perusahaan: PT Derma Enom Farma
Posisi: Electrical Engineering (Kosmetik & Farmasi)
Score: 0.13231319400300384
----------------------------------------
Perusahaan: PT Marktel
Posisi: Programmer R&D
Score: 0.1282868455078515
----------------------------------------
Perusahaan: PT Esa Sentosa Abadi Indonesia
Posisi: Mechanical Electrical Engineering
Score: 0.1271861709570582
----------------------------------------


----------------------------------------
BARIS 6
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: IT Monitoring
Score: 0.18721786368606
----------------------------------------
Perusahaan: PT. NOYA SUKSES SELALU
Posisi: IT Engineer
Score: 0.18279897299813874
----------------------------------------
Perusahaan: OrbusNeich Medical Company Limited
Posisi: IT Engineer
Score: 0.17997053847779745
----------------------------------------
Perusahaan: PT Trans Hybrid Communication
Posisi: Network Operations Center
Score: 0.17735494625858167
----------------------------------------
Perusahaan: PT Nutrifood Indonesia
Posisi: IT Application Development
Score: 0.17196726617860178
----------------------------------------


----------------------------------------
BARIS 7
----------------------------------------
Perusahaan: PT. Adika Tirta Daya
Posisi: Driver
Score: 0.20579911105399998
----------------------------------------
Perusahaan: PT Kimia Konstruksi Indonesia
Posisi: DRIVER PRIBADI
Score: 0.20115663011613924
----------------------------------------
Perusahaan: PT BSA Logistics Indonesia
Posisi: Driver Trailer (Surabaya)
Score: 0.19558714688436163
----------------------------------------
Perusahaan: Yayasan Sahid Jaya
Posisi: Driver Ketua Umum
Score: 0.19313470793632892
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Driver
Score: 0.17190114545784985
----------------------------------------


----------------------------------------
BARIS 8
----------------------------------------
Perusahaan: Hua Wen Mandarin
Posisi: Sales Admin
Score: 0.16520775140772992
----------------------------------------
Perusahaan: Murzal & Partners Law Firm
Posisi: Digital Marketing Specialist
Score: 0.13788357356272457
----------------------------------------
Perusahaan: PT Sesawi Bersaudara Medikal Industri
Posisi: QC Analyst
Score: 0.1357849517251418
----------------------------------------
Perusahaan: PT. Wiratama Anugerah Sentosa
Posisi: HRGA Manager
Score: 0.13164459889917898
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Personal Assistant
Score: 0.12738416469449296
----------------------------------------


----------------------------------------
BARIS 9
----------------------------------------
Perusahaan: PT Eusu Logistics Indonesia
Posisi: SALES MANAGER
Score: 0.2004479377313697
----------------------------------------
Perusahaan: Xiaomi Technology
Posisi: Sales Manager/ Account Manager - Balikpapan
Score: 0.19029251430624358
----------------------------------------
Perusahaan: PT GOGOBUY ECOMMERCE INDONESIA
Posisi: Business Development (Life Insurance Company Background)
Score: 0.18919940870336496
----------------------------------------
Perusahaan: Xiaomi Technology
Posisi: Sales Manager/ Account Manager - Makassar/Manado
Score: 0.18616911580535733
----------------------------------------
Perusahaan: PT Gunung Samudera Internasional
Posisi: Business Development Manager
Score: 0.17764456959636604
----------------------------------------


----------------------------------------
BARIS 10
----------------------------------------
Perusahaan: PT Mitra Sinergi Development
Posisi: ARSITEK
Score: 0.22495124551016393
----------------------------------------
Perusahaan: PT Surya Cipta Sempurna
Posisi: Arsitek
Score: 0.22033481449512604
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Quantity Surveyor (Project Based)
Score: 0.15924796170800615
----------------------------------------
Perusahaan: PT Katam Sejahtera Makmur
Posisi: Arsitek
Score: 0.14868746733048346
----------------------------------------
Perusahaan: PT Visi Fokus Sindotama Perkasa
Posisi: Project Business Consultant
Score: 0.1338376427157801
----------------------------------------

In [13]:
for no, ground_truth in enumerate(df_cv['ground_truth'].to_list(), start=1):
    print(no, ground_truth)

1 dokter umum, nurse, medical representative
2 perawat, staff nurse (perawat), private homecare nurse
3 customer service, customer relationship officer, call center officer
4 data analyst for production staff (code : prod da), pm data, jr. specialist data stewards
5 engineering staff, electrical engineering (kosmetik & farmasi), it support
6 teacher / teaching assistant / admin, ict officer, guru matematika sma
7 driver, driver pribadi, kordinator driver
8 data analyst for production staff (code : prod da), sales & marketing data analyst staf, pm data
9 sales executive, account officer / marketing, sales representative
10 arsitek, interior designer, drafter structural

In [14]:
# # manual
# baris1 = [1,0,1,1,0]
# baris2 = [1,1,1,1,0]
# baris3 = [1,1,0,1,1]
# baris4 = [0,0,0,0,0]
# baris5 = []
# baris6 = []
# baris7 = []
# baris8 = []
# baris9 = []
# baris10 = []

In [15]:
# data = pd.DataFrame({
#     'ground_truth': df_cv['ground_truth'].to_list(),
#     'hasil_prediksi': []
#     'relevan/tidak': [[] for _ in range(10)]
# })

In [16]:
# data

# TF-IDF + SVD

In [17]:
job_texts = df_job["text_for_tfidf"].tolist()

In [18]:
vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    sublinear_tf=True
)

job_tfidf = vectorizer.fit_transform(job_texts)

In [19]:
svd = TruncatedSVD(n_components=100, random_state=42)

job_svd = svd.fit_transform(job_tfidf)

In [20]:
for h in range(10):
    print("-"*40)
    print(f"BARIS {h+1}")
    print("-"*40)
    cv_text = df_cv.loc[h, 'text_for_tfidf']
    cv_tfidf = vectorizer.transform([cv_text])
    cv_svd = svd.transform(cv_tfidf)

    scores_svd = cosine_similarity(cv_svd, job_svd)

    top_k = 5
    top_indices = scores_svd[0].argsort()[-top_k:][::-1]

    for i in top_indices:
        print("Perusahaan:", df_job.iloc[i]["Perusahaan"])
        print("Posisi:", df_job.iloc[i]["Posisi"])
        print("Score:", scores_svd[0][i])
        print("-"*40)

    print("\n")

----------------------------------------
BARIS 1
----------------------------------------
Perusahaan: PT GENOMIK SOLIDARITAS INDONESIA
Posisi: Perawat Perusahaan
Score: 0.7510799251188788
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Private Homecare Nurse
Score: 0.7279133242296282
----------------------------------------
Perusahaan: Serrebeauty
Posisi: Dokter Umum
Score: 0.7222331524767647
----------------------------------------
Perusahaan: Klinik Sakti Medika
Posisi: Perawat Bedah
Score: 0.7214502161703373
----------------------------------------
Perusahaan: EUROMEDICA GROUP
Posisi: perawat
Score: 0.7113861433700511
----------------------------------------


----------------------------------------
BARIS 2
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Private Homecare Nurse
Score: 0.7696247769620093
----------------------------------------
Perusahaan: Klinik Sakti Medika
Posisi: Perawat Bedah
Score: 0.7617207325170107
----------------------------------------
Perusahaan: RS Firdaus
Posisi: Perawat
Score: 0.7503865436222433
----------------------------------------
Perusahaan: PT Bethsaida Hospital International
Posisi: Nurse (Perawat Ruang Khusus)
Score: 0.7121849942225174
----------------------------------------
Perusahaan: EUROMEDICA GROUP
Posisi: Perawat Kamar Operasi
Score: 0.7044120427500902
----------------------------------------


----------------------------------------
BARIS 3
----------------------------------------
Perusahaan: Staffinc
Posisi: Customer Service Yogyakarta
Score: 0.732876789662348
----------------------------------------
Perusahaan: Staffinc
Posisi: Customer Service Solo
Score: 0.7134074070189012
----------------------------------------
Perusahaan: PT Indotel Maju Bersama
Posisi: Agent Customer Service - English
Score: 0.6932077956135295
----------------------------------------
Perusahaan: PT Aldmic Indonesia
Posisi: Customer Service
Score: 0.6846265418547144
----------------------------------------
Perusahaan: Staffinc
Posisi: Customer Service Semarang _ English Speaker
Score: 0.6826459054175527
----------------------------------------


----------------------------------------
BARIS 4
----------------------------------------
Perusahaan: PT Airtekindo Prima
Posisi: ENGINEERING HVAC SUPERVISOR
Score: 0.6053206028445351
----------------------------------------
Perusahaan: OPPO Indonesia
Posisi: Industrial Engineer
Score: 0.5725448484634272
----------------------------------------
Perusahaan: PT Waterpro Mandiri International
Posisi: Process Engineer (WTP & WWTP)
Score: 0.5516249391407908
----------------------------------------
Perusahaan: PT Panasonic Gobel Energy Indonesia (PECGI)
Posisi: Data Analyst for Production Staff (CODE : PROD DA)
Score: 0.5387307877441048
----------------------------------------
Perusahaan: PT Uma Panca Persada
Posisi: Senior Structural Engineer
Score: 0.5363702472737237
----------------------------------------


----------------------------------------
BARIS 5
----------------------------------------
Perusahaan: PT Marktel
Posisi: Programmer R&D
Score: 0.6248788478675723
----------------------------------------
Perusahaan: PT. Sarana Meditama International (EMC Healthcare Group)
Posisi: AI Application Officer
Score: 0.6195014220331998
----------------------------------------
Perusahaan: PT. Mega Bintang Mas Indonesia
Posisi: Presales Engineering-IT Support CCTV
Score: 0.5821871070843616
----------------------------------------
Perusahaan: PT Presisi Widya
Posisi: STAF ENGINEER
Score: 0.572171882050681
----------------------------------------
Perusahaan: PT NSK Bearings Manufacturing Indonesia
Posisi: QC Staff for Digitalization Project
Score: 0.5684242114464392
----------------------------------------


----------------------------------------
BARIS 6
----------------------------------------
Perusahaan: OrbusNeich Medical Company Limited
Posisi: IT Engineer
Score: 0.7483106967679748
----------------------------------------
Perusahaan: PT. NOYA SUKSES SELALU
Posisi: IT Engineer
Score: 0.7104263630342458
----------------------------------------
Perusahaan: PT GRAVITY GAME LINK
Posisi: IT & Server Staff Engineer
Score: 0.679968525358428
----------------------------------------
Perusahaan: PT. PRASTIWAHYU TUNAS ENGINEERING
Posisi: IT STAFF
Score: 0.6710347893512505
----------------------------------------
Perusahaan: PT Rukun Persada Makmur
Posisi: IT
Score: 0.6608349257171087
----------------------------------------


----------------------------------------
BARIS 7
----------------------------------------
Perusahaan: PT BSA Logistics Indonesia
Posisi: Driver Trailer (Surabaya)
Score: 0.6922173959102645
----------------------------------------
Perusahaan: PT. Adika Tirta Daya
Posisi: Driver
Score: 0.6789523075228738
----------------------------------------
Perusahaan: PT. Chandra Ekajaya Logistik
Posisi: Kordinator Driver
Score: 0.6758157468934418
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Driver Truk Trailer / ISO Tank (Sidoarjo)
Score: 0.6436280370982385
----------------------------------------
Perusahaan: Yayasan Sahid Jaya
Posisi: Driver Ketua Umum
Score: 0.6358801959512697
----------------------------------------


----------------------------------------
BARIS 8
----------------------------------------
Perusahaan: PT Tirta Utama Abadi
Posisi: Road To Market Specialist
Score: 0.5045732476918925
----------------------------------------
Perusahaan: PT Media Wave Interaktif
Posisi: Customer Relationship Management Lead
Score: 0.47507702926620327
----------------------------------------
Perusahaan: JINISO.ID
Posisi: Data Analyst Operational
Score: 0.47280016297279126
----------------------------------------
Perusahaan: Hua Wen Mandarin
Posisi: Sales Admin
Score: 0.47074267738613224
----------------------------------------
Perusahaan: PT Parna Raya
Posisi: Manager/Kepala Bagian Humas Relasi Eksternal
Score: 0.4641123982973535
----------------------------------------


----------------------------------------
BARIS 9
----------------------------------------
Perusahaan: PT Eusu Logistics Indonesia
Posisi: SALES MANAGER
Score: 0.7101492557974869
----------------------------------------
Perusahaan: PT Jayaland
Posisi: Manajer Penjualan
Score: 0.6951294708233781
----------------------------------------
Perusahaan: KEMINDO CAO RESOURCES
Posisi: Sales Manager
Score: 0.6687331937664925
----------------------------------------
Perusahaan: PT On Time Express
Posisi: Business Development Executive
Score: 0.6563325029285451
----------------------------------------
Perusahaan: Cipta Tour (PT Biro Perjalanan Wisata Indraya Ekacipta)
Posisi: Account Executive
Score: 0.5961698609976925
----------------------------------------


----------------------------------------
BARIS 10
----------------------------------------
Perusahaan: PT Katam Sejahtera Makmur
Posisi: Arsitek
Score: 0.7017576824529586
----------------------------------------
Perusahaan: PT Mitra Sinergi Development
Posisi: ARSITEK
Score: 0.6814213845331387
----------------------------------------
Perusahaan: PT Uma Panca Persada
Posisi: Senior Structural Engineer
Score: 0.650107024097761
----------------------------------------
Perusahaan: PT Surya Cipta Sempurna
Posisi: Arsitek
Score: 0.6355116628289252
----------------------------------------
Perusahaan: PT. SANEL HESHUN SUKSES
Posisi: INTERIOR DESIGNER
Score: 0.6161445728709418
----------------------------------------

In [21]:
for no, ground_truth in enumerate(df_cv['ground_truth'].to_list(), start=1):
    print(no, ground_truth)

1 dokter umum, nurse, medical representative
2 perawat, staff nurse (perawat), private homecare nurse
3 customer service, customer relationship officer, call center officer
4 data analyst for production staff (code : prod da), pm data, jr. specialist data stewards
5 engineering staff, electrical engineering (kosmetik & farmasi), it support
6 teacher / teaching assistant / admin, ict officer, guru matematika sma
7 driver, driver pribadi, kordinator driver
8 data analyst for production staff (code : prod da), sales & marketing data analyst staf, pm data
9 sales executive, account officer / marketing, sales representative
10 arsitek, interior designer, drafter structural

# Embedding (with_punctuation)

In [22]:
job_texts = df_job["text_for_embed_with_punctuation"].tolist()

In [23]:
model = SentenceTransformer('all-MiniLM-L6-v2')
# model = SentenceTransformer('all-mpnet-base-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [24]:
job_embeddings = model.encode(job_texts, show_progress_bar=True)

Batches:   0%|          | 0/44 [00:00<?, ?it/s]

In [25]:
for h in range(10):
    print("-"*40)
    print(f"BARIS {h+1}")
    print("-"*40)
    cv_text = df_cv.loc[h, 'text_for_embed_with_punctuation']
    cv_embedding = model.encode([cv_text])

    scores_embed = cosine_similarity(cv_embedding, job_embeddings)

    top_k = 5
    top_indices = scores_embed[0].argsort()[-top_k:][::-1]

    for i in top_indices:
        print("Perusahaan:", df_job.iloc[i]["Perusahaan"])
        print("Posisi:", df_job.iloc[i]["Posisi"])
        print("Score:", scores_embed[0][i])
        print("-"*40)

    print("\n")

----------------------------------------
BARIS 1
----------------------------------------
Perusahaan: Serrebeauty
Posisi: Dokter Umum
Score: 0.7168473
----------------------------------------
Perusahaan: PT Transfarma Medica Indah
Posisi: Medical Representative (Surabaya, Jakarta, Balikpapan)
Score: 0.6527623
----------------------------------------
Perusahaan: PT Biolife Medilab
Posisi: Professional Medical Representative (Beberapa Kota)
Score: 0.63205194
----------------------------------------
Perusahaan: Nusa Medica Clinic
Posisi: Call Center Officer
Score: 0.62851584
----------------------------------------
Perusahaan: SCCR Indonesia
Posisi: Medical Representative
Score: 0.6051338
----------------------------------------


----------------------------------------
BARIS 2
----------------------------------------
Perusahaan: MAYAPADA HEALTHCARE
Posisi: HEAD OF MAYAPADA CLINIC
Score: 0.5217646
----------------------------------------
Perusahaan: Klinik Sakti Medika
Posisi: Perawat Bedah
Score: 0.514062
----------------------------------------
Perusahaan: EUROMEDICA GROUP
Posisi: perawat
Score: 0.5077985
----------------------------------------
Perusahaan: PT RADITYA ANUGERAH MEDIKA
Posisi: Nurse - Perawat
Score: 0.5045437
----------------------------------------
Perusahaan: PT BINARA GUNA MEDIKTAMA (RS. PONDOK INDAH GROUP)
Posisi: Perawat ICU
Score: 0.49304324
----------------------------------------


----------------------------------------
BARIS 3
----------------------------------------
Perusahaan: PT.Bumi Lancang kuning Pusaka (BLKP)
Posisi: Customer Relation
Score: 0.625787
----------------------------------------
Perusahaan: PT Aldmic Indonesia
Posisi: Customer Service
Score: 0.6255268
----------------------------------------
Perusahaan: Nusa Medica Clinic
Posisi: Call Center Officer
Score: 0.6180696
----------------------------------------
Perusahaan: PT Giant Transporter Indonesia
Posisi: Customer Service, Sales Support & Sales
Score: 0.59186727
----------------------------------------
Perusahaan: Staffinc
Posisi: Customer Service Semarang _ English Speaker
Score: 0.5867495
----------------------------------------


----------------------------------------
BARIS 4
----------------------------------------
Perusahaan: PT. HONGXIN ALGAE INTERNATIONAL
Posisi: Production Supervisor
Score: 0.5989642
----------------------------------------
Perusahaan: PT Sesawi Bersaudara Medikal Industri
Posisi: QC Analyst
Score: 0.5543785
----------------------------------------
Perusahaan: Ketuju by Acil Esah
Posisi: Operational Head
Score: 0.54879797
----------------------------------------
Perusahaan: PT Waterpro Mandiri International
Posisi: Process Engineer (WTP & WWTP)
Score: 0.54502743
----------------------------------------
Perusahaan: PT Glow Industri Herbal Care
Posisi: Research and Development Staff (Kosmetik & Skincare)
Score: 0.5380442
----------------------------------------


----------------------------------------
BARIS 5
----------------------------------------
Perusahaan: PT. Sarana Meditama International (EMC Healthcare Group)
Posisi: AI Application Officer
Score: 0.61343056
----------------------------------------
Perusahaan: PT. Arvirotech Global Mandiri
Posisi: Mechanical and Electrical Engineer
Score: 0.58975804
----------------------------------------
Perusahaan: PT Fajar Mulia Transindo
Posisi: Quality Assurance & IT
Score: 0.5865235
----------------------------------------
Perusahaan: PT. Berkat Maritim Abadi
Posisi: Sr. Mine Plan Engineer
Score: 0.5592414
----------------------------------------
Perusahaan: PT. Bina Juara Indonesia
Posisi: Guru Fisika SMA
Score: 0.55453795
----------------------------------------


----------------------------------------
BARIS 6
----------------------------------------
Perusahaan: PT Fajar Mulia Transindo
Posisi: Quality Assurance & IT
Score: 0.6517894
----------------------------------------
Perusahaan: PT. Sarana Meditama International (EMC Healthcare Group)
Posisi: AI Application Officer
Score: 0.63061213
----------------------------------------
Perusahaan: PT GRAVITY GAME LINK
Posisi: IT & Server Staff Engineer
Score: 0.62236166
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: IT Infrastructure Staff
Score: 0.6183613
----------------------------------------
Perusahaan: PT Luxasia Indonesia
Posisi: Trade Marketing Internship
Score: 0.61444354
----------------------------------------


----------------------------------------
BARIS 7
----------------------------------------
Perusahaan: Pengiklan Anonim
Posisi: Driver
Score: 0.57976145
----------------------------------------
Perusahaan: Yayasan Sahid Jaya
Posisi: Driver Ketua Umum
Score: 0.55893254
----------------------------------------
Perusahaan: PT Rantai Dingin Asia ( Coldspace )
Posisi: Supervisor Transport
Score: 0.54503846
----------------------------------------
Perusahaan: PT Prima Sarijati Agung
Posisi: DRIVER TAXI ONLINE BLUEBIRD
Score: 0.54180455
----------------------------------------
Perusahaan: PT. S & C MITRA ABADI
Posisi: Staff Operasional PPJK (Trucking)
Score: 0.5385693
----------------------------------------


----------------------------------------
BARIS 8
----------------------------------------
Perusahaan: PT. Berkat Citrani Mitra Sejati
Posisi: Social Media Creative (All-In-One: Video, Content & Design)
Score: 0.5280099
----------------------------------------
Perusahaan: PT DSM Nutritional Products Indonesia
Posisi: Director HR, Indonesia
Score: 0.52464557
----------------------------------------
Perusahaan: PT Cilia Prisma Utama Makmur
Posisi: Regional Sales Manager Jabodetabek
Score: 0.510924
----------------------------------------
Perusahaan: Hong Hua Mandarin Course (Jakarta Barat)
Posisi: Personal Assistant in Business Development
Score: 0.50497806
----------------------------------------
Perusahaan: CV Brasma Barsama
Posisi: Good Relationship Officer- Kalimantan Tengah #Tangguh
Score: 0.5035676
----------------------------------------


----------------------------------------
BARIS 9
----------------------------------------
Perusahaan: Xiaomi Technology
Posisi: Sales Manager/ Account Manager - Balikpapan
Score: 0.7075997
----------------------------------------
Perusahaan: Xiaomi Technology
Posisi: Sales Manager/ Account Manager - Makassar/Manado
Score: 0.69251156
----------------------------------------
Perusahaan: PT Alibarbar Industrial Indo
Posisi: Account Executive
Score: 0.6842582
----------------------------------------
Perusahaan: PT Surya Tata Alam Raya
Posisi: Customer Relation Officer
Score: 0.68074626
----------------------------------------
Perusahaan: PT Emerhub Consulting Indonesia
Posisi: Customer Success Officer
Score: 0.6796614
----------------------------------------


----------------------------------------
BARIS 10
----------------------------------------
Perusahaan: PT Katam Sejahtera Makmur
Posisi: Arsitek
Score: 0.5790997
----------------------------------------
Perusahaan: PT Mitra Sinergi Development
Posisi: ARSITEK
Score: 0.56511146
----------------------------------------
Perusahaan: Luang Building Consultant
Posisi: Tenaga Ahli Arsitek
Score: 0.5424569
----------------------------------------
Perusahaan: PT Uma Panca Persada
Posisi: Senior Structural Engineer
Score: 0.5244195
----------------------------------------
Perusahaan: Dankor
Posisi: Architect (Revit)
Score: 0.51497036
----------------------------------------

In [26]:
for no, ground_truth in enumerate(df_cv['ground_truth'].to_list(), start=1):
    print(no, ground_truth)

1 dokter umum, nurse, medical representative
2 perawat, staff nurse (perawat), private homecare nurse
3 customer service, customer relationship officer, call center officer
4 data analyst for production staff (code : prod da), pm data, jr. specialist data stewards
5 engineering staff, electrical engineering (kosmetik & farmasi), it support
6 teacher / teaching assistant / admin, ict officer, guru matematika sma
7 driver, driver pribadi, kordinator driver
8 data analyst for production staff (code : prod da), sales & marketing data analyst staf, pm data
9 sales executive, account officer / marketing, sales representative
10 arsitek, interior designer, drafter structural