In [16]:
pip install PyPDF2

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)

In [17]:
pip install deep_translator

Requirement already satisfied: deep_translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep_translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep_translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2026.4.22)

In [18]:
from PyPDF2 import PdfReader
from deep_translator import GoogleTranslator
import re
import pandas as pd
from PyPDF2 import PdfReader
import zipfile
import os

#Ekstrak zip untuk pdf beberapa cv

In [19]:

def extract_zip(zip_path, extract_to="cv_folder"):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to)
    print("✅ ZIP berhasil diekstrak")


def get_pdf_files(folder):
    pdf_files = []
    for root, dirs, files in os.walk(folder):
        for file in files:
            if file.endswith(".pdf"):
                pdf_files.append(os.path.join(root, file))
    return pdf_files

#PDF Text

In [20]:
def pdf_to_text(file_path):
    reader = PdfReader(file_path)
    text = ""
    for page in reader.pages:
        content = page.extract_text()
        if content:
            text += content + "\n"
    return text.lower()

#BASIC INFO

In [21]:
def extract_email(text):
    match = re.findall(r'\b[\w\.-]+@[\w\.-]+\.\w+\b', text)
    return match[0] if match else None


def extract_phone(text):
    match = re.findall(r'(\+62\d{9,13}|08\d{8,12})', text)
    return match[0] if match else None


def extract_name(text):
    lines = text.strip().split("\n")
    return lines[0].strip().title() if lines else None

#SECTION EXTRACTOR

In [22]:
def extract_section(text, section_names, stop_keywords):

    pattern = (
        r'(' + '|'.join(section_names) + r')'
        r'(.*?)'
        r'(?=' + '|'.join(stop_keywords) + r'|$)'
    )

    match = re.search(
        pattern,
        text,
        re.IGNORECASE | re.DOTALL
    )

    if match:
        return match.group(2).strip()

    return ""

#SKILLS

In [23]:
def extract_summary(text):

    summary = extract_section(
        text,

        section_names=[
            'ringkasan',
            'summary',
            'profil',
            'profile',
            'tentang saya',
            'about me',
            'professional summary',
            'career objective',
            'objective',
            'deskripsi diri'
        ],

        stop_keywords=[
            'pendidikan',
            'education',
            'skills',
            'keahlian',
            'organisasi',
            'experience',
            'work experience',
            'pengalaman kerja',
            'projects',
            'sertifikat',
            'certification'
        ]
    )

    # bersihkan newline
    summary = re.sub(r'\n+', ' ', summary)

    # bersihkan spasi berlebih
    summary = re.sub(r'\s+', ' ', summary)

    return summary.strip()

In [24]:
def extract_skills(text):

    lines = text.split("\n")

    skills = []
    capture = False

    start_keywords = [
        "keahlian",
        "skills",
        "skill",
        "kompetensi",
        "tools",
        "teknologi"
    ]

    stop_keywords = [
        "penghargaan",
        "bahasa",
        "hobi",
        "referensi",
        "pendidikan",
        "pengalaman",
        "organisasi"
    ]

    for line in lines:

        line = line.strip().lower()

        # mulai capture
        if any(k in line for k in start_keywords):
            capture = True
            continue

        # stop capture
        if capture and any(k in line for k in stop_keywords):
            break

        if capture:

            if not line:
                continue

            # skip line terlalu panjang
            if len(line.split()) > 10:
                continue

            # bersihkan bullet
            line = re.sub(r'^[•●▪\-]+', '', line).strip()

            skills.append(line)

    # fallback
    if not skills:

        for line in lines:

            line = line.strip().lower()

            if not line:
                continue

            # kandidat skill pendek
            if 1 <= len(line.split()) <= 5:

                if any(k in line for k in [
                    "universitas",
                    "pendidikan",
                    "pengalaman kerja",
                    "organization",
                    "address",
                    "email"
                ]):
                    continue

                skills.append(line)

    # remove duplicate
    skills = list(set(skills))

    return skills

#PENDIDIKAN

In [25]:
def extract_education(text):

    edu_text = extract_section(
        text,

        section_names=[
            'pendidikan',
            'education',
            'academic background',
            'riwayat pendidikan'
        ],

        stop_keywords=[
            'pengalaman kerja',
            'experience',
            'skills',
            'keahlian',
            'organisasi',
            'projects',
            'sertifikat',
            'certification'
        ]
    )

    edu_text = re.sub(r'\n+', ' ', edu_text)
    edu_text = re.sub(r'\s+', ' ', edu_text)

    # degree detection
    degree = None

    if any(k in edu_text.lower() for k in ['sarjana', 's1', 'bachelor']):
        degree = 'S1'

    elif any(k in edu_text.lower() for k in ['s2', 'master']):
        degree = 'S2'

    elif any(k in edu_text.lower() for k in ['d3', 'diploma']):
        degree = 'D3'

    elif 'sma' in edu_text.lower():
        degree = 'SMA'

    # university detection
    university_patterns = [
        r'universitas[\w\s]+',
        r'institut[\w\s]+',
        r'politeknik[\w\s]+',
        r'university[\w\s]+'
    ]

    university = None

    for pattern in university_patterns:

        match = re.search(pattern, edu_text, re.IGNORECASE)

        if match:
            university = match.group().strip()
            break

    return {
        "degree": degree,
        "university": university,
        "education_text": edu_text
    }

#PENGALAMAN

In [26]:
def extract_experience(text):

    exp_text = extract_section(
        text,
        section_names=[
            'pengalaman kerja',
            'work experience',
            'experience',
            'professional experience',
            'internship',
            'pengalaman'
        ],
        stop_keywords=[
            'pendidikan',
            'education',
            'skills',
            'keahlian',
            'organisasi',
            'projects',
            'sertifikat',
            'certification'
        ]
    )

    # bersihin newline berlebih
    exp_text = re.sub(r'\n+', ' ', exp_text)

    return exp_text.strip()

#ROLE

In [27]:
def extract_role(text):

    roles = [
        "data analyst",
        "data scientist",
        "software engineer",
        "frontend developer",
        "backend developer",
        "teacher",
        "admin",
        "accountant",
        "designer",
        "marketing"
    ]

    text = text.lower()

    found_roles = []

    for r in roles:
        if r in text:
            found_roles.append(r)

    return found_roles

#MAIN PARSER

In [35]:
def parse_cv(file_path):

    # extract raw text
    text = pdf_to_text(file_path)

    # basic info
    name = extract_name(text)
    email = extract_email(text)
    phone = extract_phone(text)

    # extract sections
    skills = extract_skills(text)

    summary = extract_summary(text)

    experience = extract_experience(text)

    education = extract_education(text)

    # gabungkan skills
    skills_text = ", ".join(skills)

    # full profile
    candidate_profile = f"""
    Summary:
    {summary}

    Experience:
    {experience}

    Skills:
    {skills_text}

    Education:
    {education["education_text"]}
    """

    # clean whitespace
    candidate_profile = re.sub(r'\s+', ' ', candidate_profile).strip()

    # final data
    data = {

        "candidate_name": name if name else "lorem",

        "email": email if email else "lorem",

        "phone": phone if phone else "lorem",

        "skills": skills_text if skills_text else "lorem",

        # KHUSUS SUMMARY
        "summary": summary if summary else "NONE",

        "experience": experience if experience else "lorem",

        "degree": (
            education["degree"]
            if education["degree"]
            else "lorem"
        ),

        "university": (
            education["university"]
            if education["university"]
            else "lorem"
        ),

        "education": (
            education["education_text"]
            if education["education_text"]
            else "lorem"
        ),

        "text": candidate_profile if candidate_profile else "lorem"
    }

    return data

#Data to CSV

In [36]:
def save_to_csv(data, output="hasil dari cv.csv"):
    df = pd.DataFrame([data])


    file_exists = os.path.isfile(output)

    df.to_csv(
        output,
        mode='a',
        header=not file_exists,
        index=False
    )

In [37]:
if __name__ == "__main__":

    zip_path = "/content/cv pdf.zip"

    extract_zip(zip_path)

    pdf_files = get_pdf_files("cv_folder")

    print("Jumlah CV:", len(pdf_files))

    all_results = []

    for i, pdf in enumerate(pdf_files):

        try:

          print(f"[{i+1}/{len(pdf_files)}] Processing: {pdf}")

          result = parse_cv(pdf)

          print(result)  # DEBUG

          all_results.append(result)

        except Exception as e:

          print(f"ERROR parsing {pdf}: {e}")

    # save sekali di akhir
    df = pd.DataFrame(all_results)

    df.to_csv("parsed_cv.csv", index=False)

    print("Selesai parsing semua CV")

✅ ZIP berhasil diekstrak
Jumlah CV: 366
[1/366] Processing: cv_folder/CV Siti Nurhaliza by Naevaweb (5).pdf
{'candidate_name': 'Siti Nurhaliza', 'email': 'siti.nurhaliza@example.com', 'phone': '+6281234567890', 'skills': 'penanganan keluhan, komunikasi efektif, penyelesaian masalah, manajemen panggilan, empati, zendesk, microsoft office, kepuasan pelanggan, manajemen waktu, freshdesk', 'summary': 'NONE', 'experience': 'lebih dari 2 tahun dalam menangani pertanyaan dan  keluhan pelanggan secara efisien. terbiasa bekerja di bawah tekanan dengan sikap ramah dan solusi yang  cepat. memiliki keterampilan komunikasi yang baik dan mampu membangun hubungan positif dengan  pelanggan. berkomitmen untuk memberikan pelayanan terbaik dan menjaga kepuasan pelanggan.', 'degree': 'SMA', 'university': 'lorem', 'education': 'sma negeri 2 jakarta agustus 2018 - juli 2021 sma negeri 2 jakarta jakarta jurusan: ips nilai rata-rata: 85/100', 'text': 'Summary: Experience: lebih dari 2 tahun dalam menangani pertanyaan dan keluhan pelanggan secara efisien. terbiasa bekerja di bawah tekanan dengan sikap ramah dan solusi yang cepat. memiliki keterampilan komunikasi yang baik dan mampu membangun hubungan positif dengan pelanggan. berkomitmen untuk memberikan pelayanan terbaik dan menjaga kepuasan pelanggan. Skills: penanganan keluhan, komunikasi efektif, penyelesaian masalah, manajemen panggilan, empati, zendesk, microsoft office, kepuasan pelanggan, manajemen waktu, freshdesk Education: sma negeri 2 jakarta agustus 2018 - juli 2021 sma negeri 2 jakarta jakarta jurusan: ips nilai rata-rata: 85/100'}
[2/366] Processing: cv_folder/CV Rina Aulia by Naevaweb (5).pdf
{'candidate_name': 'Rina Aulia', 'email': 'rina.aulia@example.com', 'phone': '+6281234567890', 'skills': 'komunikasi efektif, crm software, salesforce, pemecahan masalah, hubspot, zendesk, kerja tim, microsoft office, manajemen waktu', 'summary': 'NONE', 'experience': '3 tahun dalam memberikan pelayanan yang optimal  kepada pelanggan. memiliki kemampuan komunikasi yang baik, penyelesaian masalah, serta mampu bekerja  di bawah tekanan untuk memastikan kepuasan pelanggan. terampil dalam menggunakan berbagai perangkat  lunak crm dan siap berkontribusi dalam lingkungan kerja yang dinamis.', 'degree': 'D3', 'university': 'universitas lorem ipsum jakarta lulus dengan predikat cum laude', 'education': 'd3 administrasi bisnis september 2018 - juli 2021 universitas lorem ipsum jakarta lulus dengan predikat cum laude. mendalami bidang layanan pelanggan dan administrasi, serta aktif dalam kegiatan kampus seperti himpunan mahasiswa administrasi.', 'text': 'Summary: Experience: 3 tahun dalam memberikan pelayanan yang optimal kepada pelanggan. memiliki kemampuan komunikasi yang baik, penyelesaian masalah, serta mampu bekerja di bawah tekanan untuk memastikan kepuasan pelanggan. terampil dalam menggunakan berbagai perangkat lunak crm dan siap berkontribusi dalam lingkungan kerja yang dinamis. Skills: komunikasi efektif, crm software, salesforce, pemecahan masalah, hubspot, zendesk, kerja tim, microsoft office, manajemen waktu Education: d3 administrasi bisnis september 2018 - juli 2021 universitas lorem ipsum jakarta lulus dengan predikat cum laude. mendalami bidang layanan pelanggan dan administrasi, serta aktif dalam kegiatan kampus seperti himpunan mahasiswa administrasi.'}
[3/366] Processing: cv_folder/CV Anna Suryani by Naevaweb.pdf
{'candidate_name': 'Anna Suryani', 'email': 'anna.suryani@example.com', 'phone': '+6281234567890', 'skills': 'problem-solving, intern midwife august 2023 - now, compassion, delivery assistance, +6281234567891 | dr.budi@example.com, lorem ipsum community health center bogor, member october 2021 - july 2024, patient education, bachelor of midwifery september 2020 - july 2024, microsoft office, languages, hobbies, postnatal care, indonesian - native, english - fluent, university of indonesia jakarta, dr. budi santoso, pt lorem ipsum hospital, adaptability, and child health outcomes., electronic medical records (emr), reading medical journals, experience, indonesian midwives association jakarta, emergency response, best midwifery intern from pt lorem ipsum hospital (2023), references, teamwork, planning. graduated with honors (gpa: 3.75/4.00)., prenatal care, education, telemedicine platforms, pt lorem ipsum hospital jakarta, organization, awards, improving maternal health., midwifery volunteer july 2022 - september 2022', 'summary': 'NONE', 'experience': 'd in providing comprehensive care to expectant mothers and newborns. skilled in emergency  response, patient', 'degree': 'S1', 'university': 'university of indonesia jakarta focused on maternal and child health', 'education': ', and teamwork within a healthcare environment. committed to improving maternal and child health outcomes. education bachelor of midwifery september 2020 - july 2024 university of indonesia jakarta focused on maternal and child health, including prenatal and postnatal care, delivery assistance, and family planning. graduated with honors (gpa: 3.75/4.00).', 'text': 'Summary: Experience: d in providing comprehensive care to expectant mothers and newborns. skilled in emergency response, patient Skills: problem-solving, intern midwife august 2023 - now, compassion, delivery assistance, +6281234567891 | dr.budi@example.com, lorem ipsum community health center bogor, member october 2021 - july 2024, patient education, bachelor of midwifery september 2020 - july 2024, microsoft office, languages, hobbies, postnatal care, indonesian - native, english - fluent, university of indonesia jakarta, dr. budi santoso, pt lorem ipsum hospital, adaptability, and child health outcomes., electronic medical records (emr), reading medical journals, experience, indonesian midwives association jakarta, emergency response, best midwifery intern from pt lorem ipsum hospital (2023), references, teamwork, planning. graduated with honors (gpa: 3.75/4.00)., prenatal care, education, telemedicine platforms, pt lorem ipsum hospital jakarta, organization, awards, improving maternal health., midwifery volunteer july 2022 - september 2022 Education: , and teamwork within a healthcare environment. committed to improving maternal and child health outcomes. education bachelor of midwifery september 2020 - july 2024 university of indonesia jakarta focused on maternal and child health, including prenatal and postnatal care, delivery assistance, and family planning. graduated with honors (gpa: 3.75/4.00).'}
[4/366] Processing: cv_folder/CV Andi Pratama by Naevaweb (2).pdf
{'candidate_name': 'Andi Pratama', 'email': 'andi.pratama@example.com', 'phone': '+6281123456789', 'skills': 'sistem pos, komunikasi efektif, manajemen inventori, kerja sama tim, microsoft office, pengoperasian mesin espresso, meracik kopi, pelayanan pelanggan, google workspace, manajemen waktu', 'summary': 'NONE', 'experience': 'lebih dari 3 tahun di industri kopi. terampil dalam meracik berbagai jenis  minuman kopi, menjaga kebersihan area kerja, serta memiliki kemampuan komunikasi dan pelayanan  pelanggan yang baik. berkomitmen untuk selalu memberikan pengalaman kopi terbaik dan mendalami seni  dalam meracik kopi.', 'degree': 'SMA', 'university': 'lorem', 'education': 'sma negeri 3 jakarta agustus 2017 - juli 2020 sma negeri 3 jakarta jakarta jurusan: ips nilai rata-rata: 87/100', 'text': 'Summary: Experience: lebih dari 3 tahun di industri kopi. terampil dalam meracik berbagai jenis minuman kopi, menjaga kebersihan area kerja, serta memiliki kemampuan komunikasi dan pelayanan pelanggan yang baik. berkomitmen untuk selalu memberikan pengalaman kopi terbaik dan mendalami seni dalam meracik kopi. Skills: sistem pos, komunikasi efektif, manajemen inventori, kerja sama tim, microsoft office, pengoperasian mesin espresso, meracik kopi, pelayanan pelanggan, google workspace, manajemen waktu Education: sma negeri 3 jakarta agustus 2017 - juli 2020 sma negeri 3 jakarta jakarta jurusan: ips nilai rata-rata: 87/100'}
[5/366] Processing: cv_folder/CV John Doe by Naevaweb (7).pdf
{'candidate_name': 'John Doe', 'email': 'john.doe@email.com', 'phone': '+62898765432100', 'skills': 'assisted in planning and executing marketing campaigns, conducted, microsoft office, canva, google, best debater from national high school debate championship, graduated with honors, active member of the student council, and, led the student council in organizing school events, represented the, high school diploma august 2020 - july 2023, event planning, internship - marketing assistant august 2022 - september 2022, president of the student council september 2022 - july 2023, extracurricular activities. looking, student body in meetings with school administrators, and initiated, and basketball team., workspace experience, leadership, hobbies, (2022), for community service and, time management, platforms., environment. education, honor roll from lorem ipsum high school (2023), participated in various extracurricular activities including the debate club, teamwork, dynamic and challenging, lorem ipsum co. jakarta, debating, community service projects., organization, awards, lorem ipsum high school jakarta, playing basketball, public speaking, market research, and created promotional content for social media', 'summary': 'a recent high school graduate with a strong academic record and active participation in various school organizations. possesses excellent communication and leadership', 'experience': 'internship - marketing assistant august 2022 - september 2022  lorem ipsum co. jakarta  assisted in planning and executing marketing campaigns, conducted  market research, and created promotional content for social media  platforms.  organization president of the student council september 2022 - july 2023  lorem ipsum high school jakarta  led the student council in organizing school events, represented the  student body in meetings with school administrators, and initiated  community service', 'degree': 'D3', 'university': 'lorem', 'education': 'high school diploma august 2020 - july 2023 lorem ipsum high school jakarta graduated with honors, active member of the student council, and participated in various extracurricular activities including the debate club and basketball team.', 'text': 'Summary: a recent high school graduate with a strong academic record and active participation in various school organizations. possesses excellent communication and leadership Experience: internship - marketing assistant august 2022 - september 2022 lorem ipsum co. jakarta assisted in planning and executing marketing campaigns, conducted market research, and created promotional content for social media platforms. organization president of the student council september 2022 - july 2023 lorem ipsum high school jakarta led the student council in organizing school events, represented the student body in meetings with school administrators, and initiated community service Skills: assisted in planning and executing marketing campaigns, conducted, microsoft office, canva, google, best debater from national high school debate championship, graduated with honors, active member of the student council, and, led the student council in organizing school events, represented the, high school diploma august 2020 - july 2023, event planning, internship - marketing assistant august 2022 - september 2022, president of the student council september 2022 - july 2023, extracurricular activities. looking, student body in meetings with school administrators, and initiated, and basketball team., workspace experience, leadership, hobbies, (2022), for community service and, time management, platforms., environment. education, honor roll from lorem ipsum high school (2023), participated in various extracurricular activities including the debate club, teamwork, dynamic and challenging, lorem ipsum co. jakarta, debating, community service projects., organization, awards, lorem ipsum high school jakarta, playing basketball, public speaking, market research, and created promotional content for social media Education: high school diploma august 2020 - july 2023 lorem ipsum high school jakarta graduated with honors, active member of the student council, and participated in various extracurricular activities including the debate club and basketball team.'}
[6/366] Processing: cv_folder/CV John Doe by Naevaweb (4).pdf
{'candidate_name': 'John Doe', 'email': 'john.doe@example.com', 'phone': '+6281234567890', 'skills': 'collaborated with local businesses to promote sustainable tourism practices., communication, lorem ipsum travel agency denpasar, problem-solving, gpa: 3.85/4.00, english - native, indonesian - native, french - proficient, travel consultant august 2022 - now, customer relationship management (crm), travel itinerary planning, hospitality operations, sarah johnson, lorem ipsum travel agency, traveloka, microsoft office, outstanding intern award from ipsum adventure tours (2021), languages, hobbies, event coordinator september 2019 - july 2021, +6281234567891 | sarah.johnson@loremipsum.com, tourism student association yogyakarta, amadeus gds, traveling, experience, ipsum adventure tours bali, participants., tour guide intern july 2021 - october 2021, references, teamwork, achieved a 95% customer satisfaction rating based on client feedback., and tours., specialization: hospitality management, education, bachelor of tourism september 2018 - july 2022, gadjah mada university yogyakarta, provided personalized travel recommendations and managed bookings for flights, accommodations,, organization, awards, attention to detail, received positive feedback from 90% of tour participants.', 'summary': 'NONE', 'experience': 'in hospitality and customer service. skilled in travel planning,  guided tours, and creating memorable experiences for clients. excellent communication and organizational', 'degree': 'S1', 'university': 'university yogyakarta specialization', 'education': 'bachelor of tourism september 2018 - july 2022 gadjah mada university yogyakarta specialization: hospitality management gpa: 3.85/4.00 thesis: sustainable tourism development in bali: a study on eco-friendly practices', 'text': 'Summary: Experience: in hospitality and customer service. skilled in travel planning, guided tours, and creating memorable experiences for clients. excellent communication and organizational Skills: collaborated with local businesses to promote sustainable tourism practices., communication, lorem ipsum travel agency denpasar, problem-solving, gpa: 3.85/4.00, english - native, indonesian - native, french - proficient, travel consultant august 2022 - now, customer relationship management (crm), travel itinerary planning, hospitality operations, sarah johnson, lorem ipsum travel agency, traveloka, microsoft office, outstanding intern award from ipsum adventure tours (2021), languages, hobbies, event coordinator september 2019 - july 2021, +6281234567891 | sarah.johnson@loremipsum.com, tourism student association yogyakarta, amadeus gds, traveling, experience, ipsum adventure tours bali, participants., tour guide intern july 2021 - october 2021, references, teamwork, achieved a 95% customer satisfaction rating based on client feedback., and tours., specialization: hospitality management, education, bachelor of tourism september 2018 - july 2022, gadjah mada university yogyakarta, provided personalized travel recommendations and managed bookings for flights, accommodations,, organization, awards, attention to detail, received positive feedback from 90% of tour participants. Education: bachelor of tourism september 2018 - july 2022 gadjah mada university yogyakarta specialization: hospitality management gpa: 3.85/4.00 thesis: sustainable tourism development in bali: a study on eco-friendly practices'}
[7/366] Processing: cv_folder/CV Rizki Saputra by Naevaweb (2).pdf
{'candidate_name': 'Rizki Saputra', 'email': 'rizki.saputra@example.com', 'phone': '+6281234567890', 'skills': 'komunikasi efektif, manajemen persediaan, pembuatan kopi, minuman, kerja tim, microsoft office, pos system, penyajian makanan dan, pelayanan pelanggan', 'summary': 'barista berpengalaman dengan keterampilan dalam pembuatan kopi berkualitas tinggi dan pelayanan pelanggan yang ramah. memiliki pengalaman bekerja di lingkungan cepat dengan kemampuan multitasking yang baik. terbiasa dengan standar tinggi dalam menjaga kebersihan, penyimpanan bahan baku, dan memberikan pelayanan yang memuaskan kepada pelanggan.', 'experience': 'dengan keterampilan dalam pembuatan kopi  berkualitas tinggi dan pelayanan pelanggan yang ramah. memiliki  pengalaman bekerja di lingkungan cepat dengan kemampuan  multitasking yang baik. terbiasa dengan standar tinggi dalam menjaga  kebersihan, penyimpanan bahan baku, dan memberikan pelayanan yang  memuaskan kepada pelanggan.', 'degree': 'SMA', 'university': 'lorem', 'education': 'sma negeri 1 jakarta agustus 2017 - juli 2020 sma negeri 1 jakarta jakarta jurusan: ips nilai rata-rata: 85/100', 'text': 'Summary: barista berpengalaman dengan keterampilan dalam pembuatan kopi berkualitas tinggi dan pelayanan pelanggan yang ramah. memiliki pengalaman bekerja di lingkungan cepat dengan kemampuan multitasking yang baik. terbiasa dengan standar tinggi dalam menjaga kebersihan, penyimpanan bahan baku, dan memberikan pelayanan yang memuaskan kepada pelanggan. Experience: dengan keterampilan dalam pembuatan kopi berkualitas tinggi dan pelayanan pelanggan yang ramah. memiliki pengalaman bekerja di lingkungan cepat dengan kemampuan multitasking yang baik. terbiasa dengan standar tinggi dalam menjaga kebersihan, penyimpanan bahan baku, dan memberikan pelayanan yang memuaskan kepada pelanggan. Skills: komunikasi efektif, manajemen persediaan, pembuatan kopi, minuman, kerja tim, microsoft office, pos system, penyajian makanan dan, pelayanan pelanggan Education: sma negeri 1 jakarta agustus 2017 - juli 2020 sma negeri 1 jakarta jakarta jurusan: ips nilai rata-rata: 85/100'}
[8/366] Processing: cv_folder/CV Rina Putri by Naevaweb (6).pdf

In [38]:
cv_compress = pd.read_csv("/content/parsed_cv.csv")
cv_compress.head()

,candidate_name,email,phone,skills,summary,experience,degree,university,education,text
0,Siti Nurhaliza,siti.nurhaliza@example.com,6281234567890,"penanganan keluhan, komunikasi efektif, penyel...",NONE,lebih dari 2 tahun dalam menangani pertanyaan ...,SMA,lorem,sma negeri 2 jakarta agustus 2018 - juli 2021 ...,Summary: Experience: lebih dari 2 tahun dalam ...
1,Rina Aulia,rina.aulia@example.com,6281234567890,"komunikasi efektif, crm software, salesforce, ...",NONE,3 tahun dalam memberikan pelayanan yang optima...,D3,universitas lorem ipsum jakarta lulus dengan p...,d3 administrasi bisnis september 2018 - juli 2...,Summary: Experience: 3 tahun dalam memberikan ...
2,Anna Suryani,anna.suryani@example.com,6281234567890,"problem-solving, intern midwife august 2023 - ...",NONE,d in providing comprehensive care to expectant...,S1,university of indonesia jakarta focused on mat...,", and teamwork within a healthcare environment...",Summary: Experience: d in providing comprehens...
3,Andi Pratama,andi.pratama@example.com,6281123456789,"sistem pos, komunikasi efektif, manajemen inve...",NONE,lebih dari 3 tahun di industri kopi. terampil ...,SMA,lorem,sma negeri 3 jakarta agustus 2017 - juli 2020 ...,Summary: Experience: lebih dari 3 tahun di ind...
4,John Doe,john.doe@email.com,62898765432100,assisted in planning and executing marketing c...,a recent high school graduate with a strong ac...,internship - marketing assistant august 2022 -...,D3,lorem,high school diploma august 2020 - july 2023 lo...,Summary: a recent high school graduate with a ...

In [39]:
print(len(all_results))

366

In [40]:
from deep_translator import GoogleTranslator
from tqdm import tqdm
import pandas as pd
import re

# progress bar
tqdm.pandas()

# ================= TRANSLATE =================
def safe_translate(text):

    if pd.isna(text):
        return ""

    try:
        return GoogleTranslator(
            source='auto',
            target='en'
        ).translate(str(text))

    except Exception as e:
        print("Translation error:", e)
        return str(text)

# translate kolom text
cv_compress["translated_text"] = cv_compress["text"].progress_apply(safe_translate)

# ================= CLEAN TEXT =================
def clean_text(text):

    text = str(text).lower()

    # hapus simbol
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)

    # hapus spasi berlebih
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

cv_compress["clean_text"] = cv_compress["translated_text"].apply(clean_text)

# ================= SAVE =================
cv_compress.to_csv("parsed_cv_final.csv", index=False)

print("✅ File berhasil disimpan: parsed_cv_final.csv")

# preview
cv_compress.head()

100%|██████████| 366/366 [00:24<00:00, 14.70it/s]

✅ File berhasil disimpan: parsed_cv_final.csv

,candidate_name,email,phone,skills,summary,experience,degree,university,education,text,translated_text,clean_text
0,Siti Nurhaliza,siti.nurhaliza@example.com,6281234567890,"penanganan keluhan, komunikasi efektif, penyel...",NONE,lebih dari 2 tahun dalam menangani pertanyaan ...,SMA,lorem,sma negeri 2 jakarta agustus 2018 - juli 2021 ...,Summary: Experience: lebih dari 2 tahun dalam ...,Summary: Experience: more than 2 years in effi...,summary experience more than 2 years in effici...
1,Rina Aulia,rina.aulia@example.com,6281234567890,"komunikasi efektif, crm software, salesforce, ...",NONE,3 tahun dalam memberikan pelayanan yang optima...,D3,universitas lorem ipsum jakarta lulus dengan p...,d3 administrasi bisnis september 2018 - juli 2...,Summary: Experience: 3 tahun dalam memberikan ...,Summary: Experience: 3 years in providing opti...,summary experience 3 years in providing optima...
2,Anna Suryani,anna.suryani@example.com,6281234567890,"problem-solving, intern midwife august 2023 - ...",NONE,d in providing comprehensive care to expectant...,S1,university of indonesia jakarta focused on mat...,", and teamwork within a healthcare environment...",Summary: Experience: d in providing comprehens...,Summary: Experience: d in providing comprehens...,summary experience d in providing comprehensiv...
3,Andi Pratama,andi.pratama@example.com,6281123456789,"sistem pos, komunikasi efektif, manajemen inve...",NONE,lebih dari 3 tahun di industri kopi. terampil ...,SMA,lorem,sma negeri 3 jakarta agustus 2017 - juli 2020 ...,Summary: Experience: lebih dari 3 tahun di ind...,Summary: Experience: more than 3 years in the ...,summary experience more than 3 years in the co...
4,John Doe,john.doe@email.com,62898765432100,assisted in planning and executing marketing c...,a recent high school graduate with a strong ac...,internship - marketing assistant august 2022 -...,D3,lorem,high school diploma august 2020 - july 2023 lo...,Summary: a recent high school graduate with a ...,Summary: a recent high school graduate with a ...,summary a recent high school graduate with a s...

In [41]:
cv_compress = pd.read_csv("/content/parsed_cv_final.csv")
cv_compress.head()

,candidate_name,email,phone,skills,summary,experience,degree,university,education,text,translated_text,clean_text
0,Siti Nurhaliza,siti.nurhaliza@example.com,6281234567890,"penanganan keluhan, komunikasi efektif, penyel...",NONE,lebih dari 2 tahun dalam menangani pertanyaan ...,SMA,lorem,sma negeri 2 jakarta agustus 2018 - juli 2021 ...,Summary: Experience: lebih dari 2 tahun dalam ...,Summary: Experience: more than 2 years in effi...,summary experience more than 2 years in effici...
1,Rina Aulia,rina.aulia@example.com,6281234567890,"komunikasi efektif, crm software, salesforce, ...",NONE,3 tahun dalam memberikan pelayanan yang optima...,D3,universitas lorem ipsum jakarta lulus dengan p...,d3 administrasi bisnis september 2018 - juli 2...,Summary: Experience: 3 tahun dalam memberikan ...,Summary: Experience: 3 years in providing opti...,summary experience 3 years in providing optima...
2,Anna Suryani,anna.suryani@example.com,6281234567890,"problem-solving, intern midwife august 2023 - ...",NONE,d in providing comprehensive care to expectant...,S1,university of indonesia jakarta focused on mat...,", and teamwork within a healthcare environment...",Summary: Experience: d in providing comprehens...,Summary: Experience: d in providing comprehens...,summary experience d in providing comprehensiv...
3,Andi Pratama,andi.pratama@example.com,6281123456789,"sistem pos, komunikasi efektif, manajemen inve...",NONE,lebih dari 3 tahun di industri kopi. terampil ...,SMA,lorem,sma negeri 3 jakarta agustus 2017 - juli 2020 ...,Summary: Experience: lebih dari 3 tahun di ind...,Summary: Experience: more than 3 years in the ...,summary experience more than 3 years in the co...
4,John Doe,john.doe@email.com,62898765432100,assisted in planning and executing marketing c...,a recent high school graduate with a strong ac...,internship - marketing assistant august 2022 -...,D3,lorem,high school diploma august 2020 - july 2023 lo...,Summary: a recent high school graduate with a ...,Summary: a recent high school graduate with a ...,summary a recent high school graduate with a s...